language: python
python:
  - "2.7"
  - "3.7"
dist: xenial
sudo: true

env:
  global:
    - secure:

before_install:
  - python --version
  - sudo apt-get update
  - pip -V
  - pip install coveralls

install:
  - python setup.py develop
  - empiar-depositor --help

script:
  - pip install globus-cli==1.7.0
  - which empiar-depositor
  - coverage run --source=empiar_depositor setup.py test

after_success:
  - coveralls
