language: python
python:
  - "2.7"
  - "3.7"

env:
  global:
    - secure:

before_install:
  - python --version
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install -y python-dev python-pip
  - pip -V
  - pip install setuptools
  - pip install coveralls

install:
  - python setup.py develop
  - empiar-depositor --help

script:
  - pip install globus-cli==1.7.0
  - coverage run --source=/home/travis/build/emdb-empiar/empiar_depositor setup.py test

after_success:
  - coveralls
