[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "empiar-depositor"
version = "1.6.30"
# ... other metadata ...

[project.scripts]
# Command = "package_folder.filename:function"
empiar-depositor = "empiar_depositor.empiar_depositor:main"

[tool.setuptools]
# Automatically find the empiar_depositor folder
packages = ["empiar_depositor"]

[tool.setuptools.package-data]
# Ensure the schema is included in the build
"empiar_depositor" = ["*.json"]